### ISSUE TITLE
2 releases are missing on an object set in JKLThreadSafeMutableDictionary

### ISSUE THREAD

**Issue by pomarec** [jiakai-lian/JKLThreadSafeMutableCollection#1]
How to reproduce :

``` Objective-C
JKLThreadSafeMutableDictionary *dict = [JKLThreadSafeMutableDictionary new];

UIImage *image = [UIImage new];
// Breakpoint 1
dict[@"test"] = image;
// Breakpoint 2
dict[@"test"] = nil;
// Breakpoint 3
dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(5 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
    NSLog(@"image : %@", image);        // I need this to have the reference to image in the debugger
    // Breakpoint 4 (this one just checks that there is no release made asynchronously (5sec wait should be enought))
});
```

And type in the debugger at each breakpoint :

```
(lldb) po image.retainCount
1

(lldb) po image.retainCount
4

(lldb) po image.retainCount
3

2016-04-27 11:50:22.709 *****[78069:17671330] image : <UIImage: 0x7faecd16d010>, {0, 0}
(lldb) po image.retainCount
3

```

**Comment by jiakai-lian** [comment]
Hi pomarec:
Thank you for using my lib.

In terms of your question, thread safe means it is multiple threads accessable. The memory behaviour  follows the common ARC rule: This dictionary will be released when its retaincount is reduced to 0. 

To access a external variable inside a block, you need to use __block.

One example uses my lib:

```
__block JKLThreadSafeMutableDictionary *dict = [JKLThreadSafeMutableDictionary new];

UIImage *image = [UIImage new];
dict[@"test"] = image;
NSLog(@"outside image : %@", image);

dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(5 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
    NSLog(@"inside image : %@", dict[@"test"]);
});
```

2016-04-27 21:49:53.000 JKLThreadSafeMutableCollection_Example[3708:1414985] outside image : < UIImage: 0x7f83e0e0e700 >, {0, 0}
2016-04-27 21:49:58.000 JKLThreadSafeMutableCollection_Example[3708:1414985] inside image : < UIImage: 0x7f83e0e0e700 >, {0, 0}

However, you can easily achive the same goal without using any 3rd party lib.

```
__block UIImage *image = [UIImage new];
NSLog(@"outside image : %@", image);

dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(5 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
    NSLog(@"inside image : %@", image);
});
```

2016-04-27 21:52:57.334 JKLThreadSafeMutableCollection_Example[3831:1429457] outside image : < UIImage: 0x7fb730e229e0 >, {0, 0}
2016-04-27 21:53:02.334 JKLThreadSafeMutableCollection_Example[3831:1429457] inside image : < UIImage: 0x7fb730e229e0 >, {0, 0}

**Comment by jiakai-lian** [comment]
Sorry. I believe I misunderstood your question.

For the retain count issue, the retain count is not reliable in the era of ARC so far from I know.
The framework may do something behind the scene and you may not be aware of it.
[http://stackoverflow.com/questions/4636146/when-to-use-retaincount](url)

I did few tests on Instruments:Leaks, and  turned on the ZombieObjects for further investigation. So far no memory issue are founded.

I will try to do more tests in a more complex context.
If you found more information about the memory issue, please do let me know.
Thanks.

**Comment by pomarec** [comment]
My bad. I have no other information. Thanks for your quick answer :)

**Comment by pomarec** [comment]
Nice lib BTW, clear and focused on one task.
